// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/storage/docentry.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	IndexName     string                 `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	Key           *Key                   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Document      []byte                 `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentEntry) Reset() {
	*x = DocumentEntry{}
	mi := &file_pkg_storage_docentry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentEntry) ProtoMessage() {}

func (x *DocumentEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_docentry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentEntry.ProtoReflect.Descriptor instead.
func (*DocumentEntry) Descriptor() ([]byte, []int) {
	return file_pkg_storage_docentry_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentEntry) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *DocumentEntry) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *DocumentEntry) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DocumentEntry) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

type Key struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Key_IntValue
	//	*Key_StringValue
	//	*Key_BoolValue
	//	*Key_FloatValue
	//	*Key_DateValue
	Value         isKey_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_pkg_storage_docentry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_docentry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_pkg_storage_docentry_proto_rawDescGZIP(), []int{1}
}

func (x *Key) GetValue() isKey_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Key) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Key_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Key) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Key_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Key) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Key_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Key) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Key_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *Key) GetDateValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Key_DateValue); ok {
			return x.DateValue
		}
	}
	return 0
}

type isKey_Value interface {
	isKey_Value()
}

type Key_IntValue struct {
	IntValue int64 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Key_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Key_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Key_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type Key_DateValue struct {
	DateValue int64 `protobuf:"varint,5,opt,name=date_value,json=dateValue,proto3,oneof"` // UnixNano
}

func (*Key_IntValue) isKey_Value() {}

func (*Key_StringValue) isKey_Value() {}

func (*Key_BoolValue) isKey_Value() {}

func (*Key_FloatValue) isKey_Value() {}

func (*Key_DateValue) isKey_Value() {}

type MultiIndexEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Keys          map[string]*Key        `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Document      []byte                 `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiIndexEntry) Reset() {
	*x = MultiIndexEntry{}
	mi := &file_pkg_storage_docentry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiIndexEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiIndexEntry) ProtoMessage() {}

func (x *MultiIndexEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_docentry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiIndexEntry.ProtoReflect.Descriptor instead.
func (*MultiIndexEntry) Descriptor() ([]byte, []int) {
	return file_pkg_storage_docentry_proto_rawDescGZIP(), []int{2}
}

func (x *MultiIndexEntry) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *MultiIndexEntry) GetKeys() map[string]*Key {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *MultiIndexEntry) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

var File_pkg_storage_docentry_proto protoreflect.FileDescriptor

const file_pkg_storage_docentry_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/storage/docentry.proto\x12\astorage\"\x89\x01\n" +
	"\rDocumentEntry\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1d\n" +
	"\n" +
	"index_name\x18\x02 \x01(\tR\tindexName\x12\x1e\n" +
	"\x03key\x18\x03 \x01(\v2\f.storage.KeyR\x03key\x12\x1a\n" +
	"\bdocument\x18\x04 \x01(\fR\bdocument\"\xb7\x01\n" +
	"\x03Key\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vfloat_value\x18\x04 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1f\n" +
	"\n" +
	"date_value\x18\x05 \x01(\x03H\x00R\tdateValueB\a\n" +
	"\x05value\"\xcb\x01\n" +
	"\x0fMultiIndexEntry\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x126\n" +
	"\x04keys\x18\x02 \x03(\v2\".storage.MultiIndexEntry.KeysEntryR\x04keys\x12\x1a\n" +
	"\bdocument\x18\x03 \x01(\fR\bdocument\x1aE\n" +
	"\tKeysEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.storage.KeyR\x05value:\x028\x01B0Z.github.com/bobboyms/storage-engine/pkg/storageb\x06proto3"

var (
	file_pkg_storage_docentry_proto_rawDescOnce sync.Once
	file_pkg_storage_docentry_proto_rawDescData []byte
)

func file_pkg_storage_docentry_proto_rawDescGZIP() []byte {
	file_pkg_storage_docentry_proto_rawDescOnce.Do(func() {
		file_pkg_storage_docentry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_storage_docentry_proto_rawDesc), len(file_pkg_storage_docentry_proto_rawDesc)))
	})
	return file_pkg_storage_docentry_proto_rawDescData
}

var file_pkg_storage_docentry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_storage_docentry_proto_goTypes = []any{
	(*DocumentEntry)(nil),   // 0: storage.DocumentEntry
	(*Key)(nil),             // 1: storage.Key
	(*MultiIndexEntry)(nil), // 2: storage.MultiIndexEntry
	nil,                     // 3: storage.MultiIndexEntry.KeysEntry
}
var file_pkg_storage_docentry_proto_depIdxs = []int32{
	1, // 0: storage.DocumentEntry.key:type_name -> storage.Key
	3, // 1: storage.MultiIndexEntry.keys:type_name -> storage.MultiIndexEntry.KeysEntry
	1, // 2: storage.MultiIndexEntry.KeysEntry.value:type_name -> storage.Key
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_storage_docentry_proto_init() }
func file_pkg_storage_docentry_proto_init() {
	if File_pkg_storage_docentry_proto != nil {
		return
	}
	file_pkg_storage_docentry_proto_msgTypes[1].OneofWrappers = []any{
		(*Key_IntValue)(nil),
		(*Key_StringValue)(nil),
		(*Key_BoolValue)(nil),
		(*Key_FloatValue)(nil),
		(*Key_DateValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_storage_docentry_proto_rawDesc), len(file_pkg_storage_docentry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_storage_docentry_proto_goTypes,
		DependencyIndexes: file_pkg_storage_docentry_proto_depIdxs,
		MessageInfos:      file_pkg_storage_docentry_proto_msgTypes,
	}.Build()
	File_pkg_storage_docentry_proto = out.File
	file_pkg_storage_docentry_proto_goTypes = nil
	file_pkg_storage_docentry_proto_depIdxs = nil
}
